In [ ]:
import numpy as np
import matplotlib.pyplot as plt

###Uso del método iterativo de Gauss-Seidel para aproximar la solución
$$
x=\left[\begin{array}{rrr}
x_1 & x_2 & x_3
\end{array}\right]^T
$$
###al sistema lineal
$$
AX=B
$$
###con una tolerancia de $10^{-2}$ y un máximo de 300 iteraciones.
$$
\begin{aligned}
x_1- x_3 & = & 0.2 \\
-\frac{1}{2} x_1+x_2-\frac{1}{4} x_3 & = & -1.425 \\
x_1-\frac{1}{2} x_2 +x_3 & = & 2
\end{aligned}
$$
Donde se tienen las matrices
$$
A=\left[\begin{array}{rrr}
1 & 0 & -1 \\
-\frac{1}{2} & 1 & -\frac{1}{4} \\
1 & -\frac{1}{2} & 1
\end{array}\right]
$$
y el vector
$$
B=\left[\begin{array}{rrr}
0.2 & -1.425 & 2
\end{array}\right]^T
$$



###Gauss Seidel de la forma

$$x_i^{(k+1)}=\frac{1}{a_{i i}}\left(b_i-\sum_{j<i} a_{i j} x_j^{(k+1)}-\sum_{j>i} a_{i j} x_j^{(k)}\right)$$

In [ ]:
#Matriz A
A=np.array([[1,0,-1],
            [-0.5,1,-0.25],
            [1,-0.5,1]])
#vector B
b=np.array([0.2,-1.425,2])
solucion = np.linalg.inv(A).dot(b)

In [ ]:
print("La solución exacta del sistema es: ", solucion)

La solución exacta del sistema es:  [ 0.9 -0.8  0.7]


Una matriz $A$ es estrictamente diagonalmente dominante si para todo $i \in 1, \ldots, n$,
\begin{equation*}
            |a_{ii}| > \sum_{\substack{j=1 \\ j \neq i}}^n |a_{ij}|
        \end{equation*}

In [ ]:
def EdiagonalDominante(A):
    sum = []
    diagonal = []
    for i in range(A.shape[0]):
        suma = 0
        for j in range(A.shape[1]):
            if i != j:
                suma += abs(A[i,j])
            else:
                diagonal.append(A[i,j])
        sum.append(suma)
    lista = []
    for i in range(len(diagonal)):
        if diagonal[i] <= sum[i]:
            lista.append(0)
        else:
            lista.append(1)
    if 0 in lista:
      print("No es estrictamente diagonal dominante")
    else:
      print("Es estrictamente diagonal dominante")

EdiagonalDominante(A)

No es estrictamente diagonal dominante


###Punto a)
La matriz
$$
A=\left[\begin{array}{rrr}
1 & 0 & -1 \\
-\frac{1}{2} & 1 & -\frac{1}{4} \\
1 & -\frac{1}{2} & 1
\end{array}\right]
$$
no es estrictamente diagonal dominante

Tenemos que la matriz de Gauss - Seidel es de la forma

$$M_{GS} = I-Q^{-1}A,\quad \text{con} \quad C_L\text{ es matriz inferior} \quad Q=D+C_L$$

### Punto b)
Entonces el radio espectral es

\begin{equation*}
    \rho(M_{GS})= \max_{\lambda \in σ(A)} |λ| = 5/8 = 0.625
\end{equation*}

que a su vez es menor a 1 y se concluye en efecto que Gauss-Seidel converge.

In [ ]:
def radioEspectralGS(A):
    Q = np.zeros(A.shape)
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if j <= i:
                Q[i,j] = A[i,j]
    Mgs = np.identity(A.shape[0]) - np.linalg.inv(Q)@A
    radio_espectral = max(abs(np.linalg.eigvals(Mgs)))
    print("El radio espectral de Mgs es:", radio_espectral)

radioEspectralGS(A)

El radio espectral de Mgs es: 0.625


In [ ]:
def gauss_seidel(A, b, x0, tolerancia, itermax):
    n = len(A)
    x = x0.copy()

    for i in range(itermax):
        x_actualizado = np.zeros(n)
        for j in range(n):
            suma1 = np.dot(A[j, :j], x_actualizado[:j])
            suma2 = np.dot(A[j, j + 1:], x[j + 1:])
            x_actualizado[j] = (b[j] - suma1 - suma2) / A[j, j]
        if np.allclose(x, x_actualizado, tolerancia):
            return x_actualizado
        x = x_actualizado
    return x

In [ ]:
x0 = np.array([0, 0 , 0])
tolerancia = 0.01
itermax = 300
x = gauss_seidel(A, b, x0, tolerancia, itermax)
print("Solución por Gauss - Seidel")
print(x)

Solución por Gauss - Seidel
[ 0.8975131  -0.80186517  0.70155431]


Qué pasa si el sistema se cambia por:
$$
\begin{aligned}
x_1-2 x_3 & = & 0.2 \\
-\frac{1}{2} x_1+x_2-\frac{1}{4} x_3 & = & -1.425 \\
x_1-\frac{1}{2}x_2 +x_3 & = & 2
\end{aligned}
$$
con matriz
$$
A=\left[\begin{array}{rrr}
1 & 0 & -2 \\
-\frac{1}{2} & 1 & -\frac{1}{4} \\
1 & -\frac{1}{2} & 1
\end{array}\right]
$$
y el vector
$$
B=\left[\begin{array}{rrr}
0.2 & -1.425 & 2
\end{array}\right]^T
$$

In [ ]:
#Matriz A
W=np.array([[1,0,-2],
            [-0.5,1,-0.25],
            [1,-0.5,1]])

x0 = np.array([0, 0 , 0])
tolerancia = 0.01
itermax = 300
x = gauss_seidel(W, b, x0, tolerancia, itermax)
EdiagonalDominante(W)
radioEspectralGS(W)
print("Solución por Gauss - Seidel")
print(x)

No es estrictamente diagonal dominante
El radio espectral de Mgs es: 1.375
Solución por Gauss - Seidel
[ 2.15687283e+41  1.34804552e+41 -1.48285007e+41]


Ahora con el metodo de Jacobi
La sucesión se construye descomponiendo la matriz del sistema $A$ en la forma siguiente:
$$
A=D+R
$$
donde $D$, es una matriz diagonal y $R$, es la suma de una matriz triangular inferior $L$ y una matriz triangular superior $U$, luego $R=L+U$. Partiendo de $A \mathbf{x}=\mathbf{b}$, podemos reescribir dicha ecuación como
$$
D \mathbf{x}+R \mathbf{x}=\mathbf{b}
$$
Luego,
$$
\mathbf{x}=D^{-1}(\mathbf{b}-R \mathbf{x})
$$
Si $a_{i j} \neq 0$ para cada $i$. Por la regla iterativa, la definición del Método de Jacobi puede ser expresado de la forma:
$$
\mathbf{x}^{(k+1)}=D^{-1}\left(\mathbf{b}-R \mathbf{x}^{(k)}\right)
$$
donde $k$ es el contador de iteración, Finalmente tenemos:
$$
x_i^{(k+1)}=\frac{1}{a_{i i}}\left(b_i-\sum_{j \neq i} a_{i j} x_j^{(k)}\right), i=1,2,3, \ldots
$$

In [ ]:
def jacobi(A,b,x0,itermax, tolerancia):
    x = x0.copy()
    D = np.zeros(A.shape)

    for i in range(len(D)):
        D[i,i] = A[i,i]
    W = A - D
    for i in range(itermax):
        x = np.dot(np.linalg.inv(D), b - np.dot(W,x))
        if np.allclose(solucion, x, tolerancia):
            return x
    return x

La matriz de Jacobi es de la forma
\begin{equation*}
        M_{J}= I - D^{-1}A
\end{equation*}

Entonces el radio espectral es

\begin{equation*}
    \rho(M_{J})= \max_{\lambda \in σ(A)} |λ| = 5/8 = 0.972
\end{equation*}

y se concluye que Jacobi converge

In [ ]:
def radEspectralJ(A):
    D = np.zeros(A.shape)
    for i in range(len(D)):
        D[i,i] = A[i,i]
    MJ = np.identity(A.shape[0]) - np.linalg.inv(D)@A
    radio_espectral = max(abs(np.linalg.eigvals(MJ)))
    print("El radio espectral de Tg es:", radio_espectral)

radEspectralJ(A)

El radio espectral de Tg es: 0.9721052103388309


In [ ]:
x0 = np.array([0, 0 , 0])
tolerancia = 0.01
max_iterations = 300
X=jacobi(A,b,x0,itermax, tolerancia)
print("Solución por Jacobi")
print(X)

Solución por Jacobi
[ 0.89200332 -0.80340885  0.7047798 ]


Cambiando la matriz A por

$$
A=\left[\begin{array}{rrr}
1 & 0 & -2 \\
-\frac{1}{2} & 1 & -\frac{1}{4} \\
1 & -\frac{1}{2} & 1
\end{array}\right]
$$

In [ ]:
#Matriz A
W=np.array([[1,0,-2],
            [-0.5,1,-0.25],
            [1,-0.5,1]])

x0 = np.array([0, 0 , 0])
tolerancia = 0.01
itermax = 300
radEspectralJ(W)
X = jacobi(W,b,x0,itermax, tolerancia)
print("Solución por Gauss - Seidel")
print(x)

El radio espectral de Tg es: 1.3933177928644842
Solución por Gauss - Seidel
[ 2.15687283e+41  1.34804552e+41 -1.48285007e+41]
